/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RestImport } from './routes/rest'
import { Route as GraphqlImport } from './routes/graphql'

// Create/Update Routes

const RestRoute = RestImport.update({
  id: '/rest',
  path: '/rest',
  getParentRoute: () => rootRoute,
} as any)

const GraphqlRoute = GraphqlImport.update({
  id: '/graphql',
  path: '/graphql',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/graphql': {
      id: '/graphql'
      path: '/graphql'
      fullPath: '/graphql'
      preLoaderRoute: typeof GraphqlImport
      parentRoute: typeof rootRoute
    }
    '/rest': {
      id: '/rest'
      path: '/rest'
      fullPath: '/rest'
      preLoaderRoute: typeof RestImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/graphql': typeof GraphqlRoute
  '/rest': typeof RestRoute
}

export interface FileRoutesByTo {
  '/graphql': typeof GraphqlRoute
  '/rest': typeof RestRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/graphql': typeof GraphqlRoute
  '/rest': typeof RestRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/graphql' | '/rest'
  fileRoutesByTo: FileRoutesByTo
  to: '/graphql' | '/rest'
  id: '__root__' | '/graphql' | '/rest'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  GraphqlRoute: typeof GraphqlRoute
  RestRoute: typeof RestRoute
}

const rootRouteChildren: RootRouteChildren = {
  GraphqlRoute: GraphqlRoute,
  RestRoute: RestRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/graphql",
        "/rest"
      ]
    },
    "/graphql": {
      "filePath": "graphql.tsx"
    },
    "/rest": {
      "filePath": "rest.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
