/**
 * @fileoverview gRPC-Web generated client stub for charts
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.6.1
// source: charts.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as charts_pb from './charts_pb'; // proto import: "charts.proto"
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"


export class ChartServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetChartData = new grpcWeb.MethodDescriptor(
    '/charts.ChartService/GetChartData',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    charts_pb.ChartDataList,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    charts_pb.ChartDataList.deserializeBinary
  );

  getChartData(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<charts_pb.ChartDataList>;

  getChartData(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: charts_pb.ChartDataList) => void): grpcWeb.ClientReadableStream<charts_pb.ChartDataList>;

  getChartData(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: charts_pb.ChartDataList) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/charts.ChartService/GetChartData',
        request,
        metadata || {},
        this.methodDescriptorGetChartData,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/charts.ChartService/GetChartData',
    request,
    metadata || {},
    this.methodDescriptorGetChartData);
  }

}

